//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
