//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thamdo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thamdo()
        {
            this.ctthamdoes = new HashSet<ctthamdo>();
        }
    
        public int MaCH { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string NoiDungThamDo { get; set; }
        public Nullable<int> TongSoBinhChon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctthamdo> ctthamdoes { get; set; }
    }
}
