//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vietgiay
    {
        public int MaTG { get; set; }
        public int MaGiay { get; set; }
        public string VaiTro { get; set; }
    
        public virtual giay giay { get; set; }
        public virtual tacgia tacgia { get; set; }
    }
}
